### PR TITLE
Frontend Skeleton

### PR DESCRIPTION
**Pull request by esheehan-gsl**
Create a skeleton for the frontend so that we can test building and deploying the frontend to AWS once that infrastructure becomes available.

## Overview

There’s an [nvmrc](https://github.com/nvm-sh/nvm) to help you set get the right version of Node.

### Run the development server locally
```bash
npm run dev
```

### Build the application
```bash
npm run build
cp -r node_modules/@uswds/uswds/dist/fonts build
```

I was unable to configure SvelteKit/Vite to copy the fonts from USWDS into our `build/` directory. I think this is something that can either be handled in CI or when building the Docker image.

### Run the tests
```bash
npm run test
```

## To Do
- [x] Add SvelteKit skeleton
- [x] Configure US Web Design System
- [x] `npm run build` compiles a static app
- [x] Lint styles and scripts
  - [x] Enforce an order for the CSS properties
- [x] Add a base layout with a header and placeholder body

### CODE REVIEW

**Comment by esheehan-gsl** [comment]
@ian-noaa I don’t know how much time you want to spend looking over this change—there’s a lot of boilerplate. But I thought I’d give you a heads up to see if there’s anything you’d like to see in here that is missing, or something you’d like done differently.

I haven’t set up the Docker image yet because I’m waiting until we know more about the Kubernetes infrastructure, but I could definitely add the Dockerfile now, if you’d like.

**Comment by ian-noaa** [comment]
Thanks, Evan. I went ahead and got the development server up and running on my local machine and it's looking good! Ditto for the `.editorconfig` and the other project setup files. One question I had - is there a good way to run the application from the production build directory locally? Or would we hand that to e.g. Apache/Nginx?

It looks like they're still working on the infrastructure. However, if you wouldn't mind adding the Dockerfile, I could go ahead and work on setting up CI while we wait on that. Once we have a container, we can at least start working with Kubernetes locally in Rancher Desktop.

**Comment by esheehan-gsl** [comment]
Running in dev is a tricky question. Typically frontend developers like to run the application using a dev server (like Vite, which is what we use) that provides incremental builds and live reloads. That’s what you run when you execute `npm run dev`.

With SvelteKit, you can preview the production version of the application using the `preview` script, like this:

```bash
npm run build
npm run preview
```

Which will run a web server out of the `build/` directory with the built files. (The Vite dev server doesn’t pre-compile most of this, it gets built on-demand, I think, to make the cold-start faster in development.)

For the production container, we’ll probably want a two-stage build:
1. Grab a Node container
2. `npm install && npm build`
3. Grab a webserver container
4. Copy the build and fonts to `/var/www/html` (or whatever)

I see the value in using that container in development, since it eliminates disparities between dev and production, but I don’t see how we maintain the advantages of all the Node tools there. Maybe it’s ok to development using the dev server, and spin up k8s with the production containers locally for testing?

**Comment by ian-noaa** [comment]
Gotcha. Thanks for that explainer. So it sounds like `npm run dev` is shorthand for `npm run build && npm run preview` - is that a valid takeaway?

That sounds like what I was imagining as far as the Docker build, as well. The advantage of the multistage build is that we could also potentially use the Node image as a development container down the road if desired.

I agree that the incremental builds and live reloads are valuable and we want to keep that capability. I think doing development with the local npm dev server, and then building the production containers and loading them in k8s locally if we need to do end-to-end testing with the backend is a good way to go for now. I'll eventually need the ability to make sure that the Kubernetes config we use is set up correctly so having the containers around will be handy for that as well.

I've heard of a few ways to do development within a Kubernetes cluster with e.g. - VSCode or a tool like Skaffold. So they could be interesting to experiment with. However, it seems like it's still early days and I don't want to be in the position where we're required to use a particular IDE or have to do arcane workarounds for development.

**Comment by esheehan-gsl** [comment]
> So it sounds like `npm run dev` is shorthand for `npm run build && npm run preview` - is that a valid takeaway?

No, not exactly. `npm run dev` starts up a development server that watches for changes to the source, incrementally compiles them, and then updates the running application in the browser automatically. `npm run build` compiles all of the source (Svelte components, SCSS, _etc._) into a set of static files for production. `npm run preview` runs a vanilla web server out of the directory containing the built files, similar to how they’d be served in production by Apache or Nginx.

If you start `npm run dev`, load http://localhost:3000 in a browser, open `src/routes/index.svelte`, and make a change to the text there, when you switch over to the browser, you’ll see that your change is already visible in the browser without you even having to hit the refresh button. If you repeat this process, but replace `npm run dev` with `npm run build && npm run preview`, you won’t see the change in the browser; you’d have to kill the process and rerun `npm run build && npm run preview` before the change was available.

The process for `npm run dev` is completely unlike the processes that would be used in production, which is why SvelteKit provides the `preview` command. One way in which this difference manifests is that on a cold start, when you load the app for the first time, you’ll see serif fonts on the page for a few seconds before it switches to sans-serif and applies our layouts. This is because the dev server compiles our base styles from SCSS on-demand, and USWDS is a bit slow to build, so when the page first loads, those styles aren’t available. Once they become available, Vite injects them into the page, and the appearance changes. This doesn’t happen if you build and preview because the styles are compiled to CSS at build time so they are ready when the page loads.

I’ve thought about using the Node stage of the image for a dev environment. It might be worthwhile if it makes networking simpler, but if our goal is an environment that matches production, we can’t really achieve that using the dev server (for the reasons I outlined above). For that reason I was thinking we’d just use the dev server locally, if we can, and then when we’re testing before a merge, we can spin up the whole cluster and run our tests using an environment that matches production.

**Comment by ian-noaa** [comment]
Ah, I was forgetting about the hot reload part you mentioned earlier and was thinking `npm run dev` was basically doing `npm run build && npm run preview` as it detected page changes. But that'd still leave you needing to refresh the page to pull the changes in. 

I definitely experienced the cold start for `npm run dev` as it compiled the SCSS styles so thanks for calling that out! 

As for local dev environments, containers, and Kubernetes - I agree that using the dev server locally makes a lot of sense unless we encounter a compelling reason to do development in the container. And I also think doing final testing using the production images is the way to go so we can make sure we match production closely. So I believe we're on the same page there. Regarding the cluster; would you want to be able to spin up a cluster locally during development or would you rather leave that to CI and have it spin up one in AWS?

**Comment by esheehan-gsl** [comment]
I think it’d be good to have the ability to run the production environment locally, assuming it’s not to resource intensive. But it’s not the end of the world if we’re running it in CI for testing.

**Review by ian-noaa — APPROVED** [review]
Sounds good. I'll keep looking into that. Did you want to add the Dockerfile in this PR? Or did you want to do the Dockerfile in a separate PR?

**Pull request merged**
