### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by esheehan-gsl**

### CODE REVIEW

**Comment by esheehan-gsl** [comment]
@ian-noaa when you get back, I’d love to get your thoughts about code coverage. I’ve updated both services so that they measure it. Right now they’re both writing out the reports to stdout in the actions, so we can see the results there, but it’s kinda buried.

I have the api service generating an HTML report and storing it as an artifact, but that doesn’t seem to be very useful, since you have to download and… I guess open a `file:///…` URL on your computer to view it? I was unable to find any information about getting GitHub to surface the results the way GitLab can if you give it an xunit file.

Maybe this is why people put those image badges in their READMEs? I suppose that’s something we could look into.

**Comment by esheehan-gsl** [comment]
Alright, I don’t know what’s going on with the code coverage PR comment. It doesn’t seem to be running. But the workflow will fail if code coverage isn’t above the minimum threshold, so that’s probably good.

**Comment by ian-noaa** [comment]
Oh weird, it looks like CI isn't running in general for this PR. I'm going to have to think on this one for a minute - based on the files that were changed here it should be running builds for both services.

**Comment by esheehan-gsl** [comment]
@ian-noaa are we ok merging this? I think the workflows should fail if code coverage is too low. It’d be great to improve reporting, but at least we have checks we can find.

**Pull request merged**
