### PR TITLE
Parse additional model metadata during ingest

### PR DESCRIPTION
**Pull request by esheehan-gsl**
Process information necessary for data selection in the UI from the S3 key and
the file name. New data being read is:

- Model (RRFS, RTMA, HRRR)
- System (Jet, WCOSS, Hera, etc…)
- Background (only relevant to the 3D-RTMA - could be HRRR or RRFS)
- Domain (North America, CONUS, Alaska, Puerto Rico, Guam, American Samoa, Caribbean, etc…)
- Frequency (Realtime vs Retro)

## Stacked PRs

- #242

### CODE REVIEW

**Comment by esheehan-gsl** [comment]
@ian-noaa I’m going to stack the changes to the app that read this data and present it in the UI on top of this one, but I think the updates to the pipeline are ready to review.

**Comment by esheehan-gsl** [comment]
@ian-noaa You may want to give this one a second look, because I had to make a few changes after your last review. Sorry. I had forgotten to account for the background in our group paths.

**Comment by ian-noaa** [comment]
Thanks for the heads up. So I can keep up - why did we need to switch from the path separator to underscores? I missed the motivation behind that. Does it make it easier to grab the metadata with the regex?

Either way, the changes look good.

**Comment by esheehan-gsl** [comment]
The `/` separator is present in the key on S3, but when we download the files, we convert `/` to `_` (we’ve always been doing this, it’s just that it didn’t matter before). We use the entire key as the filename for the file, rather than creating a directory structure in `/tmp/` that matches the path in the key, which is a lot easier than having to recursively make directories.

**Pull request merged**
