### PR TITLE
Fetch diagnostics as JSON over HTTP

### PR DESCRIPTION
**Pull request by esheehan-gsl**
Define API for fetching temperature diagnostics as JSON over HTTP. For now there is no ability to choose a model run, since we have only one set of test files. We will focus on temperature first, and then add other variables.

### CODE REVIEW

**Comment by esheehan-gsl** [comment]
@ian-noaa let me know what you think of this approach to testing our API.

I’ve created an abstraction for retrieving the diagnostics data in the `diag.py` module. It will provide an interface for the routes in the API to request the data without the routes having to know anything about where that data is stored (on local disk, in S3, as NetCDF, as Zarr, _etc._).

Aside from making it easier for us to change our data store without having to touch the routes it makes it easier for us to provide test data for the routes, because we can just mock the `get_diagnostics()` function (as I’ve done here) to return whatever test data we want and assert the full response in our tests based on known data. This way we don’t have to build and commit test NetCDF files to the repo just to run unit tests against the API.

I still have a lot of work to do to get the route doing anything useful, but I wanted to run this testing approach by you sooner rather than later.

**Comment by ian-noaa** [comment]
I think the approach here looks good. I like that we'll have an interface for the routes to request data without the routes needing to know about the backend storage. To your point - it seems like it'll make it easier to test both the routes and the diagnostic processing in isolation.

**Comment by esheehan-gsl** [comment]
@ian-noaa do you have any idea how to fix this libc vulnerability in the API docker container? Do we need to run `apt-get upgrade` in the Dockerfile to get the version that’s been fixed?

**Comment by ian-noaa** [comment]
Good question - I did some digging into this this morning. 

Traditionally, I've heard that running `apt-get upgrade` in a Dockerfile is a bad practice. I did explore other Python images (`python:3.9-slim-bullseye` and `python:3.9-alpine`) and they appear to pass Trivy's scanning. However, I think it's only a matter of time until we run into a similar security issue with those images; and we'd have the added complexity of dealing with minimal dependencies in Debian slim or trying to manage Python dependencies in Alpine with their musl libc. (I could see this being particularly problematic with e.g. NumPy as they have significant C/C++ components that would need to be recompiled)

I took a bit more of a look at running `apt-get upgrade` and it does solve the security issue we're seeing here. Moreover, it appears that the guidance on running `apt-get upgrade` has changed. [OWASP](https://github.com/OWASP/CheatSheetSeries/pull/614), [Docker](https://github.com/docker/docker.github.io/pull/12571), and [hadolint](https://github.com/hadolint/hadolint/issues/562) have all removed their recommendations against running OS upgrades based on this article: https://pythonspeed.com/articles/security-updates-in-docker/

Given that, I think we should go ahead and apply OS updates whenever we build our images. I was using the following in `services/api/Dockerfile` so that caching would still work for us:

```diff
FROM python:3.9

WORKDIR /usr/src/app

RUN pip3 install gunicorn poetry \
    && poetry config virtualenvs.create false

COPY . .

RUN poetry install --no-interaction --no-ansi --no-dev
+ RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*

EXPOSE 80
CMD ["gunicorn", "unified_graphics.wsgi:app", "--bind=0.0.0.0:80"]
```

**Comment by esheehan-gsl** [comment]
Oh, good shout about updating `CONTRIBUTING.md`. I’ll get that done this afternoon.

I’ll also start a ticket for integration tests and we can track the S3 bucket stuff there.

**Comment by esheehan-gsl** [comment]
@ian-noaa I updated `CONTRIBUTING`, is that what you were looking for?

**Comment by ian-noaa** [comment]
Yeah, that looks great. Thanks! It'll be nice to have with all the context-switching going on.

**Pull request merged**
